apiVersion: v1
kind: Service

metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: platform-services
    # Security classification label
    security.platform.io/classification: restricted

spec:
  type: {{ .Values.service.type }}
  # Internal cluster DNS configuration
  clusterIP: None
  # Port configuration for auth service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
      protocol: TCP
      name: http
      # Support for metrics scraping
      appProtocol: http
  
  # Pod selector using helm template helper
  selector:
    {{- include "auth-service.selectorLabels" . | nindent 4 }}
  
  # Session affinity for consistent routing
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
  
  # Publishing service configuration  
  publishNotReadyAddresses: false
  
  # Internal traffic policy for security
  internalTrafficPolicy: Cluster