# Service template for monitoring service exposing metrics, health checks, and tracing endpoints
# Version: 1.0.0
apiVersion: v1
kind: Service

metadata:
  name: {{ include "monitoring-service.fullname" . }}
  labels:
    {{- include "monitoring-service.labels" . | nindent 4 }}
  annotations:
    # Prometheus scraping configuration
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
    prometheus.io/scheme: "http"
    # Service type annotation for discovery
    monitoring.kubernetes.io/service-type: "metrics-health-tracing"
    # Service description
    service.kubernetes.io/description: "Monitoring service exposing metrics, health checks, and tracing endpoints"
    # Service version
    service.kubernetes.io/version: "1.0.0"
    # Update timestamp
    service.kubernetes.io/last-updated: {{ now | quote }}

spec:
  type: ClusterIP
  # Port configuration for different monitoring endpoints
  ports:
    # Prometheus metrics endpoint
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
      appProtocol: http
    
    # Health check endpoint
    - port: 8080
      targetPort: health
      protocol: TCP
      name: health
      appProtocol: http
    
    # Distributed tracing endpoint
    - port: 16686
      targetPort: tracing
      protocol: TCP
      name: tracing
      appProtocol: http

  # Selector for pod discovery
  selector:
    {{- include "monitoring-service.selectorLabels" . | nindent 4 }}