apiVersion: v1
kind: Secret
metadata:
  name: workflow-platform-secrets
  namespace: workflow-platform
  labels:
    app: workflow-platform
    environment: production
    managed-by: terraform
    rotation-enabled: "true"
  annotations:
    # Monthly rotation schedule
    rotation.kubernetes.io/schedule: "0 0 1 * *"
    # Enable audit logging
    audit.kubernetes.io/enabled: "true"
    # Backup every 6 hours
    backup.kubernetes.io/schedule: "0 */6 * * *"
    # Additional security annotations
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "workflow-platform"
    encryption.kubernetes.io/mode: "aes-gcm"
    encryption.kubernetes.io/key-version: "1"

type: Opaque
data:
  # AI Service Secrets
  OPENAI_API_KEY: ${OPENAI_API_KEY_BASE64}
  PINECONE_API_KEY: ${PINECONE_API_KEY_BASE64}
  PINECONE_ENVIRONMENT: ${PINECONE_ENV_BASE64}

  # Authentication Service Secrets
  JWT_SECRET: ${JWT_SECRET_BASE64}
  JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET_BASE64}
  OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID_BASE64}
  OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET_BASE64}

  # Database Secrets
  DB_PASSWORD: ${DB_PASSWORD_BASE64}
  REDIS_PASSWORD: ${REDIS_PASSWORD_BASE64}
  SMTP_PASSWORD: ${SMTP_PASSWORD_BASE64}

---
# RBAC Role for Secret Access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: workflow-platform
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["workflow-platform-secrets"]
  verbs: ["get"]

---
# Role Binding for AI Service
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-service-secret-reader
  namespace: workflow-platform
subjects:
- kind: ServiceAccount
  name: ai-service
  namespace: workflow-platform
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io

---
# Role Binding for Auth Service
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-service-secret-reader
  namespace: workflow-platform
subjects:
- kind: ServiceAccount
  name: auth-service
  namespace: workflow-platform
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io

---
# Secret Rotation CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-rotation-job
  namespace: workflow-platform
spec:
  schedule: "0 0 1 * *"  # Monthly rotation
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: secret-rotator
          containers:
          - name: secret-rotator
            image: workflow-platform/secret-rotator:1.0.0
            env:
            - name: SECRET_NAME
              value: workflow-platform-secrets
            - name: NAMESPACE
              value: workflow-platform
          restartPolicy: OnFailure

---
# Secret Backup CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-backup-job
  namespace: workflow-platform
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: secret-backup
          containers:
          - name: secret-backup
            image: workflow-platform/secret-backup:1.0.0
            env:
            - name: SECRET_NAME
              value: workflow-platform-secrets
            - name: BACKUP_BUCKET
              value: workflow-platform-backups
          restartPolicy: OnFailure