apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai-engine
    service.kubernetes.io/monitoring: "true"
  annotations:
    prometheus.io/scrape: "{{ .Values.monitoring.enabled }}"
    prometheus.io/path: "{{ .Values.monitoring.path }}"
    prometheus.io/port: "{{ .Values.monitoring.port }}"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.env.PORT }}
      protocol: TCP
    {{- if .Values.monitoring.enabled }}
    - name: metrics
      port: {{ .Values.monitoring.port }}
      targetPort: {{ .Values.monitoring.port }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ai-engine
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
  publishNotReadyAddresses: false
  # Enable internal traffic policy for better security
  internalTrafficPolicy: Cluster