# Helm Chart for Authentication Service
# Node.js Version: 20 LTS
# Last Updated: 2023
apiVersion: v2
name: auth-service
description: Enterprise-grade authentication service providing OAuth 2.0, JWT-based authentication, MFA support, and comprehensive security features with SOC2 and HIPAA compliance

# Chart type and version information
type: application
version: 1.0.0
appVersion: 1.0.0

# Keywords for chart discovery and categorization
keywords:
  - authentication
  - oauth2
  - jwt
  - security
  - mfa
  - rbac
  - compliance
  - soc2
  - hipaa
  - gdpr

# Chart maintainers
maintainers:
  - name: Platform Security Team
    email: security@workflow.com
  - name: Authentication Team
    email: auth@workflow.com

# Chart dependencies
dependencies:
  - name: common
    version: 1.0.0
    repository: file://../common
    condition: common.enabled

# Security and compliance annotations
annotations:
  security.workflow.com/compliance: soc2,hipaa,gdpr
  security.workflow.com/features: oauth2,jwt,mfa,rbac
  security.workflow.com/scanRequired: "true"
  security.workflow.com/securityContext: enabled
  security.workflow.com/mfaRequired: "true"
  security.workflow.com/auditLogging: enabled
  security.workflow.com/dataEncryption: aes256
  security.workflow.com/tlsVersion: "1.3"
  security.workflow.com/rbacEnabled: "true"

# Home URL and documentation
home: https://github.com/workflow/auth-service
sources:
  - https://github.com/workflow/auth-service

# Additional metadata
icon: https://workflow.com/icons/auth-service.png
kubeVersion: ">=1.21.0"